version: '3'

services:
  drupal-service:
    build:
      context: .
      dockerfile: drupal.Dockerfile
    image: drupal-custom
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-themes:/var/www/html/themes
      - drupal-sites:/var/www/html/sites
    ports:
      - '8080:80'
    depends_on:
      - drupal_service_db

  drupal_service_db:
    image: postgres
    environment:
      - POSTGRES_DB=drupal_service
      - POSTGRES_USER=peter
      - POSTGRES_PASSWORD=drupaltest21%
    volumes:
      - drupal-data:/var/lib/postgresql/data

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-themes:
  drupal-sites:
  drupal-data:
